create table librarian(
    id serial not null primary key,
	name varchar(100),
	cpf varchar(11),
	email varchar(100),
	phone varchar(11),
	password varchar(100)
);

create table student(
    id serial not null primary key,
    name varchar(100),
    phone varchar(11),
    registration varchar(50)
);

create table book(
    id serial not null primary key,
	name varchar(100),
	author varchar(100),
	yearOfPublication Integer,
	publishingCompany varchar(100),
	quantity Integer
);

create table emprestimo(
	id serial not null generated by default as identity primary key,
	id_book serial not null,
	constraint id_book foreign key (id_book) references book(id),

	id_student serial not null,
	constraint id_student foreign key (id_student) references student(id),

	withdrawnDate date not null,
	returnDate date,
	deadline date not null,
	trafficTicket boolean not null
);